// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAedH-rOONXDzGMbEelZFGefFITqowFvpc',
    appId: '1:921598381469:android:7b0edc1a6a0f527ee1f374',
    messagingSenderId: '921598381469',
    projectId: 'mvc-app-2',
    storageBucket: 'mvc-app-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPNu_9ijfN8IgzmpohXMIAgq4jLemJOFo',
    appId: '1:921598381469:ios:100770aa40826f36e1f374',
    messagingSenderId: '921598381469',
    projectId: 'mvc-app-2',
    storageBucket: 'mvc-app-2.appspot.com',
    iosBundleId: 'com.example.mvcApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuwlhcz1ArlztZ0h7pmSLqN-6sHyV4BQc',
    appId: '1:921598381469:web:89b4dfe0db6ef6e1e1f374',
    messagingSenderId: '921598381469',
    projectId: 'mvc-app-2',
    authDomain: 'mvc-app-2.firebaseapp.com',
    storageBucket: 'mvc-app-2.appspot.com',
    measurementId: 'G-0LVLBBFJRC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPNu_9ijfN8IgzmpohXMIAgq4jLemJOFo',
    appId: '1:921598381469:ios:100770aa40826f36e1f374',
    messagingSenderId: '921598381469',
    projectId: 'mvc-app-2',
    storageBucket: 'mvc-app-2.appspot.com',
    iosBundleId: 'com.example.mvcApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuwlhcz1ArlztZ0h7pmSLqN-6sHyV4BQc',
    appId: '1:921598381469:web:cb78ff61ead0213be1f374',
    messagingSenderId: '921598381469',
    projectId: 'mvc-app-2',
    authDomain: 'mvc-app-2.firebaseapp.com',
    storageBucket: 'mvc-app-2.appspot.com',
    measurementId: 'G-3TN0HLZC75',
  );

}